import type { Transaction, Account, Budget, Category } from "$lib/types.js";
import { finance } from "./finance.svelte.js";
import { getCurrentMonth } from "$lib/utils.js";

const categories: Category[] = [
	{ id: "cat-salary", name: "Salary", type: "income", color: "#22c55e" },
	{ id: "cat-freelance", name: "Freelance", type: "income", color: "#10b981" },
	{ id: "cat-groceries", name: "Groceries", type: "expense", color: "#f97316" },
	{ id: "cat-dining", name: "Dining", type: "expense", color: "#ef4444" },
	{ id: "cat-transport", name: "Transportation", type: "expense", color: "#3b82f6" },
	{ id: "cat-entertainment", name: "Entertainment", type: "expense", color: "#a855f7" },
	{ id: "cat-utilities", name: "Utilities", type: "expense", color: "#eab308" },
	{ id: "cat-shopping", name: "Shopping", type: "expense", color: "#ec4899" },
	{ id: "cat-health", name: "Health", type: "expense", color: "#14b8a6" },
	{ id: "cat-subscriptions", name: "Subscriptions", type: "expense", color: "#6366f1" },
];

const accounts: Account[] = [
	{
		id: "acc-checking",
		name: "Main Checking",
		type: "checking",
		balance: 425000,
		currency: "USD",
	},
	{
		id: "acc-savings",
		name: "Savings",
		type: "savings",
		balance: 1280000,
		currency: "USD",
	},
	{
		id: "acc-credit",
		name: "Credit Card",
		type: "credit_card",
		balance: -134000,
		currency: "USD",
	},
	{
		id: "acc-cash",
		name: "Cash",
		type: "cash",
		balance: 18000,
		currency: "USD",
	},
];

function getDateStr(monthsAgo: number, day: number): string {
	const d = new Date();
	d.setMonth(d.getMonth() - monthsAgo);
	d.setDate(day);
	return d.toISOString().slice(0, 10);
}

const currentMonth = getCurrentMonth();

function buildTransactions(): Transaction[] {
	return [
		// Current month
		{
			id: "tx-01",
			date: getDateStr(0, 1),
			description: "Monthly Salary",
			amount: 520000,
			type: "income",
			categoryId: "cat-salary",
			accountId: "acc-checking",
		},
		{
			id: "tx-02",
			date: getDateStr(0, 3),
			description: "Whole Foods Market",
			amount: 8745,
			type: "expense",
			categoryId: "cat-groceries",
			accountId: "acc-checking",
		},
		{
			id: "tx-03",
			date: getDateStr(0, 4),
			description: "Uber ride to office",
			amount: 2350,
			type: "expense",
			categoryId: "cat-transport",
			accountId: "acc-checking",
		},
		{
			id: "tx-04",
			date: getDateStr(0, 5),
			description: "Netflix subscription",
			amount: 1599,
			type: "expense",
			categoryId: "cat-subscriptions",
			accountId: "acc-credit",
		},
		{
			id: "tx-05",
			date: getDateStr(0, 6),
			description: "Trader Joe's",
			amount: 6230,
			type: "expense",
			categoryId: "cat-groceries",
			accountId: "acc-checking",
		},
		{
			id: "tx-06",
			date: getDateStr(0, 7),
			description: "Electric bill",
			amount: 12400,
			type: "expense",
			categoryId: "cat-utilities",
			accountId: "acc-checking",
		},
		{
			id: "tx-07",
			date: getDateStr(0, 8),
			description: "Freelance project payment",
			amount: 150000,
			type: "income",
			categoryId: "cat-freelance",
			accountId: "acc-checking",
		},
		{
			id: "tx-08",
			date: getDateStr(0, 9),
			description: "Chipotle",
			amount: 1485,
			type: "expense",
			categoryId: "cat-dining",
			accountId: "acc-credit",
		},
		{
			id: "tx-09",
			date: getDateStr(0, 10),
			description: "Amazon - headphones",
			amount: 7999,
			type: "expense",
			categoryId: "cat-shopping",
			accountId: "acc-credit",
		},
		{
			id: "tx-10",
			date: getDateStr(0, 11),
			description: "Gym membership",
			amount: 4999,
			type: "expense",
			categoryId: "cat-health",
			accountId: "acc-checking",
		},
		{
			id: "tx-11",
			date: getDateStr(0, 12),
			description: "Spotify Premium",
			amount: 1099,
			type: "expense",
			categoryId: "cat-subscriptions",
			accountId: "acc-credit",
		},
		{
			id: "tx-12",
			date: getDateStr(0, 13),
			description: "Target",
			amount: 4520,
			type: "expense",
			categoryId: "cat-shopping",
			accountId: "acc-credit",
		},
		{
			id: "tx-13",
			date: getDateStr(0, 14),
			description: "Gas station",
			amount: 4800,
			type: "expense",
			categoryId: "cat-transport",
			accountId: "acc-checking",
		},
		{
			id: "tx-14",
			date: getDateStr(0, 15),
			description: "Sushi restaurant",
			amount: 6200,
			type: "expense",
			categoryId: "cat-dining",
			accountId: "acc-credit",
		},
		{
			id: "tx-15",
			date: getDateStr(0, 16),
			description: "Internet bill",
			amount: 7999,
			type: "expense",
			categoryId: "cat-utilities",
			accountId: "acc-checking",
		},
		{
			id: "tx-16",
			date: getDateStr(0, 17),
			description: "Movie tickets",
			amount: 3200,
			type: "expense",
			categoryId: "cat-entertainment",
			accountId: "acc-cash",
		},
		// Last month
		{
			id: "tx-17",
			date: getDateStr(1, 1),
			description: "Monthly Salary",
			amount: 520000,
			type: "income",
			categoryId: "cat-salary",
			accountId: "acc-checking",
		},
		{
			id: "tx-18",
			date: getDateStr(1, 5),
			description: "Whole Foods Market",
			amount: 9200,
			type: "expense",
			categoryId: "cat-groceries",
			accountId: "acc-checking",
		},
		{
			id: "tx-19",
			date: getDateStr(1, 8),
			description: "Electric bill",
			amount: 11800,
			type: "expense",
			categoryId: "cat-utilities",
			accountId: "acc-checking",
		},
		{
			id: "tx-20",
			date: getDateStr(1, 10),
			description: "Italian restaurant",
			amount: 8500,
			type: "expense",
			categoryId: "cat-dining",
			accountId: "acc-credit",
		},
		{
			id: "tx-21",
			date: getDateStr(1, 12),
			description: "Freelance web design",
			amount: 200000,
			type: "income",
			categoryId: "cat-freelance",
			accountId: "acc-checking",
		},
		{
			id: "tx-22",
			date: getDateStr(1, 14),
			description: "Costco groceries",
			amount: 15600,
			type: "expense",
			categoryId: "cat-groceries",
			accountId: "acc-checking",
		},
		{
			id: "tx-23",
			date: getDateStr(1, 16),
			description: "Concert tickets",
			amount: 12000,
			type: "expense",
			categoryId: "cat-entertainment",
			accountId: "acc-credit",
		},
		{
			id: "tx-24",
			date: getDateStr(1, 18),
			description: "Uber rides",
			amount: 3500,
			type: "expense",
			categoryId: "cat-transport",
			accountId: "acc-checking",
		},
		{
			id: "tx-25",
			date: getDateStr(1, 20),
			description: "Nike shoes",
			amount: 12999,
			type: "expense",
			categoryId: "cat-shopping",
			accountId: "acc-credit",
		},
		{
			id: "tx-26",
			date: getDateStr(1, 22),
			description: "Internet bill",
			amount: 7999,
			type: "expense",
			categoryId: "cat-utilities",
			accountId: "acc-checking",
		},
		// 2 months ago
		{
			id: "tx-27",
			date: getDateStr(2, 1),
			description: "Monthly Salary",
			amount: 520000,
			type: "income",
			categoryId: "cat-salary",
			accountId: "acc-checking",
		},
		{
			id: "tx-28",
			date: getDateStr(2, 4),
			description: "Grocery outlet",
			amount: 7800,
			type: "expense",
			categoryId: "cat-groceries",
			accountId: "acc-checking",
		},
		{
			id: "tx-29",
			date: getDateStr(2, 7),
			description: "Thai restaurant",
			amount: 4200,
			type: "expense",
			categoryId: "cat-dining",
			accountId: "acc-credit",
		},
		{
			id: "tx-30",
			date: getDateStr(2, 10),
			description: "Electric bill",
			amount: 13500,
			type: "expense",
			categoryId: "cat-utilities",
			accountId: "acc-checking",
		},
		{
			id: "tx-31",
			date: getDateStr(2, 13),
			description: "Bus pass",
			amount: 10000,
			type: "expense",
			categoryId: "cat-transport",
			accountId: "acc-checking",
		},
		{
			id: "tx-32",
			date: getDateStr(2, 15),
			description: "Freelance consulting",
			amount: 100000,
			type: "income",
			categoryId: "cat-freelance",
			accountId: "acc-checking",
		},
		{
			id: "tx-33",
			date: getDateStr(2, 18),
			description: "Amazon - books",
			amount: 4500,
			type: "expense",
			categoryId: "cat-shopping",
			accountId: "acc-credit",
		},
		{
			id: "tx-34",
			date: getDateStr(2, 20),
			description: "Doctor visit copay",
			amount: 3000,
			type: "expense",
			categoryId: "cat-health",
			accountId: "acc-checking",
		},
		{
			id: "tx-35",
			date: getDateStr(2, 22),
			description: "Streaming services",
			amount: 2500,
			type: "expense",
			categoryId: "cat-subscriptions",
			accountId: "acc-credit",
		},
		// 3 months ago
		{
			id: "tx-36",
			date: getDateStr(3, 1),
			description: "Monthly Salary",
			amount: 520000,
			type: "income",
			categoryId: "cat-salary",
			accountId: "acc-checking",
		},
		{
			id: "tx-37",
			date: getDateStr(3, 6),
			description: "Whole Foods",
			amount: 11200,
			type: "expense",
			categoryId: "cat-groceries",
			accountId: "acc-checking",
		},
		{
			id: "tx-38",
			date: getDateStr(3, 10),
			description: "Mexican restaurant",
			amount: 5500,
			type: "expense",
			categoryId: "cat-dining",
			accountId: "acc-credit",
		},
		{
			id: "tx-39",
			date: getDateStr(3, 14),
			description: "Gas station",
			amount: 5200,
			type: "expense",
			categoryId: "cat-transport",
			accountId: "acc-checking",
		},
		{
			id: "tx-40",
			date: getDateStr(3, 18),
			description: "Video game purchase",
			amount: 5999,
			type: "expense",
			categoryId: "cat-entertainment",
			accountId: "acc-credit",
		},
	];
}

function buildBudgets(): Budget[] {
	const month = getCurrentMonth();
	return [
		{ id: "bud-01", categoryId: "cat-groceries", allocated: 60000, period: month },
		{ id: "bud-02", categoryId: "cat-dining", allocated: 30000, period: month },
		{ id: "bud-03", categoryId: "cat-transport", allocated: 20000, period: month },
		{ id: "bud-04", categoryId: "cat-entertainment", allocated: 15000, period: month },
		{ id: "bud-05", categoryId: "cat-utilities", allocated: 25000, period: month },
		{ id: "bud-06", categoryId: "cat-shopping", allocated: 40000, period: month },
	];
}

export function seedIfEmpty() {
	if (finance.hasData) return;

	finance.categories = categories;
	finance.accounts = accounts;
	finance.transactions = buildTransactions();
	finance.budgets = buildBudgets();
	finance.persist();
}
